/***************************************************************
* Copyright (C) 2018
*    Computer Graphics Support Group of 30 Phys-Math Lyceum
***************************************************************/

/* FILE NAME   : MTH.H
 * PURPOSE     : Math support.
 *               Finale module module.
 * PROGRAMMER  : CGSG'2018.
 *               Filippov Denis.
 * LAST UPDATE : 20.07.2018.
 * NOTE        : None.
 *
 * No part of this file may be changed without agreement of
 * Computer Graphics Support Group of 30 Phys-Math Lyceum.
 */

#ifndef __MTH_H_
#define __MTH_H_

#include "vec.h"
#include "matr.h"
#include "camera.h"

/* Type defenition */
typedef mth::vec<FLT> vec;
typedef mth::vec2<FLT> vec2;
typedef mth::vec4<FLT> vec4;
typedef mth::matr<FLT> matr;

#endif /* __MTH_H_ */

/* END OF 'MTH.H' FILE */


