#include "def.h"
/*
int main( void )
{
  FLT len, dot;
  mth::vec<FLT> V1(3, 0, 0), V2(0, 4, 0), V3;
  mth::matr<FLT> 
    M1(1, 0, 0, 0,
       0, 1, 0, 0,
       0, 0, 1, 0,
       0, 0, 0, 1),
    M2, 
    M3(1, 0, 0, 0,
       0, 0, 0, 0,
       0, 0, 0, 0,
       0, 0, 0, 0);

  len = sqrt(V1.Length2());
  len = sqrt(V1.Distance2(V2));
  V3 = V1 + V2;
  V3 = V2 - V2;
  V2 += V1;
  V2 -= V2;
  V2 = V1 / 3;
  V2 = V1 * 3;
  V2 *= 4;
  V2 /= 4;
  dot = V1 & V2;
  V3 = V1 % V2;
  V3.Rnd();
  V3.Zero();
  V3 = -V1 + V2;
  return 0;
};
*/